tunnel: exdraw-tunnel
credentials-file: ./cloudflared/exdraw-tunnel.json

ingress:
  - hostname: myexdraw.aastar.io
    path: /api/v2/*
    service: http://localhost:9888
  - hostname: myexdraw.aastar.io
    service: http://localhost:9887
  - service: http_status:404
